# Generated by Django 4.1.4 on 2022-12-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signupfeilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email_address', models.EmailField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=128)),
            ],
        ),
    ]
