# Generated by Django 4.1.4 on 2023-01-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cards',
        ),
    ]
